# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            "Latif Atci"
tagline:          ''
description:      ''
url:              "https://latifatci.com"
baseurl:          /

plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag

author:
  name:           'Latif Atci'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version: 3.0.0

github:
  repo:           https://github.com/poole/hyde
